#!/usr/bin/env python3

# Convert reveal.js HTML slides to a PDF file with Playwright.
#
# Call reveal2pdf.py -h for help with the command-line options.
# NOTE: Use the container image to run this without local installation of Python or Playwright. See README.adoc.

import argparse
import asyncio
from playwright.async_api import async_playwright


parser = argparse.ArgumentParser(
    prog='reveal2pdf',
    description='Converts HTML slides generated by reveal.js to PDF files'
)

parser.add_argument('html_url', help='HTML slides input URL (?print-pdf will be appended). Example: file:///opt/prj/slides.html')
parser.add_argument('pdf_path', help='PDF output file. Example: /opt/prj/slides.pdf')

args = parser.parse_args()

args.html_url += '?print-pdf'

print(f"html_url: {args.html_url}")
print(f"pdf_path: {args.pdf_path}")


async def url_to_pdf(url, output_path):
    async with async_playwright() as p:
        browser = await p.chromium.launch()
        page = await browser.new_page()
        await page.emulate_media(media='print')
        await page.goto(url, wait_until='networkidle')
        await page.locator(".reveal.ready").wait_for()
        await page.pdf(path=output_path, print_background=True, prefer_css_page_size=True)

        await browser.close()

asyncio.run(url_to_pdf(args.html_url, args.pdf_path))
